# Generated by Django 4.1.2 on 2022-10-30 18:18

import accounts.models
from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('additional_names', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), null=True, size=10, verbose_name='additional names')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation date')),
                ('email', models.EmailField(max_length=255, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='email address')),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='phone number')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', accounts.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='name')),
                ('description', models.CharField(max_length=150, unique=True, verbose_name='description')),
                ('permissions', models.ManyToManyField(blank=True, to='auth.permission', verbose_name='permissions')),
            ],
            options={
                'verbose_name': 'applicationrole',
                'verbose_name_plural': 'applicationroles',
            },
            managers=[
                ('objects', accounts.models.ApplicationRoleManager()),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationAccount',
            fields=[
                ('address1', models.CharField(max_length=50, verbose_name='Address line 1')),
                ('address2', models.CharField(blank=True, max_length=50, verbose_name='Address line 2')),
                ('state', models.CharField(max_length=20, verbose_name='State')),
                ('zip_code', models.CharField(max_length=12, verbose_name='ZIP')),
                ('company', models.CharField(max_length=20, verbose_name='Company')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='name')),
                ('email', models.EmailField(max_length=255, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='email address')),
                ('status', models.CharField(choices=[('S', 'Submitted'), ('A', 'Approved'), ('C', 'Cancelled')], max_length=1)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation date')),
                ('ownerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='applicationuser',
            name='accountid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.applicationaccount'),
        ),
        migrations.AddField(
            model_name='applicationuser',
            name='applicationroles',
            field=models.ManyToManyField(blank=True, help_text='The role this user is assigned to. A user will get all permissions granted to each of their roles.', related_name='applicationuser_set', related_query_name='applicationuser', to='accounts.applicationrole', verbose_name='applicationroles'),
        ),
        migrations.AddField(
            model_name='applicationuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='applicationuser_set', related_query_name='applicationuser', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='applicationuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='applicationuser_set', related_query_name='applicationuser', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
