# Generated by Django 4.1.2 on 2022-10-30 07:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_applicationuser_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationuser',
            name='additional_names',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), size=10, verbose_name='additional names'),
        ),
    ]
