# Generated by Django 4.1.2 on 2022-10-30 20:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_applicationuser_accountid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationaccount',
            name='email',
            field=models.EmailField(max_length=255, validators=[django.core.validators.EmailValidator()], verbose_name='email address'),
        ),
    ]
