# Generated by Django 4.1.2 on 2022-10-30 08:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_applicationuser_additional_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationuser',
            name='additional_names',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), null=True, size=10, verbose_name='additional names'),
        ),
    ]
