# Generated by Django 4.1.2 on 2022-10-30 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_applicationaccount_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resourcekind', models.CharField(choices=[('RFDataContract', 'Reinforcement learning data contract'), ('MLModel', 'Machine learning model'), ('MLInput', 'Machine learning input data'), ('RFModel', 'Reinforcement learning model')], max_length=20)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('accountid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.applicationaccount')),
                ('createrid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
