# Generated by Django 4.1.2 on 2022-12-06 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0003_settinggroup_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='settingvalue',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
