# Generated by Django 4.1.2 on 2022-12-06 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0004_alter_setting_settingvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='settingname',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='settingvalue',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
