# Generated by Django 4.1.2 on 2022-11-27 14:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('settingname', models.CharField(max_length=20, unique=True)),
                ('settingvalue', models.CharField(max_length=20)),
            ],
        ),
    ]
