# Generated by Django 4.1.2 on 2022-12-04 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0004_remove_setting_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SettingGroup',
        ),
    ]
