# Generated by Django 4.1.2 on 2022-12-04 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0005_delete_settinggroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='settingname',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='settingvalue',
        ),
    ]
