# Generated by Django 4.1.2 on 2022-12-04 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configurator', '0006_remove_setting_owner_remove_setting_settingname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='settingname',
            field=models.CharField(default=None, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='settingvalue',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
