# Generated by Django 4.1.2 on 2022-12-04 17:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0007_setting_owner_setting_settingname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('groupname', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='setting',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='configurator.settinggroup'),
        ),
    ]
