# Generated by Django 4.1.2 on 2022-12-04 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0008_settinggroup_setting_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='group',
        ),
        migrations.DeleteModel(
            name='SettingGroup',
        ),
    ]
