# Generated by Django 4.1.2 on 2022-12-04 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='settingname',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='settingvalue',
        ),
    ]
