# Generated by Django 4.1.2 on 2022-12-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0002_remove_setting_settingname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='settingname',
            field=models.CharField(default=None, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='settingvalue',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
